In [7]:
#Loading the required packages

import pandas as pd
import matplotlib as pyplot 
import seaborn as sn

In [23]:
#loading the data
Rental = pd.read_csv("/Users/nyadual/Desktop/Canada_Cost_of_Living/Rental_Prices_databaseLoadingData.csv")
Rental.head()

,REF_DATE,GEO,DGUID,Rental unit type,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,Jan-20,"St. John's, Census metropolitan area (CMA)",2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,810.0,NaN,NaN,NaN,0
1,Apr-20,"St. John's, Census metropolitan area (CMA)",2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,860.0,NaN,NaN,NaN,0
2,Jul-20,"St. John's, Census metropolitan area (CMA)",2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,860.0,NaN,NaN,NaN,0
3,Oct-20,"St. John's, Census metropolitan area (CMA)",2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,850.0,NaN,NaN,NaN,0
4,Jan-21,"St. John's, Census metropolitan area (CMA)",2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,870.0,NaN,NaN,NaN,0

In [20]:
#cleaning the rental data
#remove CMA in the GEO column

Rental["GEO"] = Rental["GEO"].str.replace(",.*", "", regex=True).str.strip()
Rental.head()

,REF_DATE,GEO,DGUID,Rental unit type,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,Jan-20,St. John's,2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,810.0,NaN,NaN,NaN,0
1,Apr-20,St. John's,2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,860.0,NaN,NaN,NaN,0
2,Jul-20,St. John's,2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,860.0,NaN,NaN,NaN,0
3,Oct-20,St. John's,2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,850.0,NaN,NaN,NaN,0
4,Jan-21,St. John's,2021S0503001,Apartment - 1 bedroom,Average asking rent,Dollars,81,units,0,v1675424962,1.2.1,870.0,NaN,NaN,NaN,0

In [24]:
#remove the unwanted columns
Rental = Rental[["REF_DATE", "GEO", "Rental unit type", "Estimates", "VALUE"]]

#Change columns name
Rental = Rental.rename(columns = {"VALUE": "Rental_value"})

# Convert date
Rental["REF_DATE"] = pd.to_datetime(Rental["REF_DATE"], format="%b-%y")
Rental["Year"] = Rental["REF_DATE"].dt.year
Rental["Quarter"] = Rental["REF_DATE"].dt.quarter

Rental.head()

,REF_DATE,GEO,Rental unit type,Estimates,Rental_value,Year,Quarter
0,2020-01-01,"St. John's, Census metropolitan area (CMA)",Apartment - 1 bedroom,Average asking rent,810.0,2020,1
1,2020-04-01,"St. John's, Census metropolitan area (CMA)",Apartment - 1 bedroom,Average asking rent,860.0,2020,2
2,2020-07-01,"St. John's, Census metropolitan area (CMA)",Apartment - 1 bedroom,Average asking rent,860.0,2020,3
3,2020-10-01,"St. John's, Census metropolitan area (CMA)",Apartment - 1 bedroom,Average asking rent,850.0,2020,4
4,2021-01-01,"St. John's, Census metropolitan area (CMA)",Apartment - 1 bedroom,Average asking rent,870.0,2021,1

In [30]:
#Pvoting Rental data

Rental = Rental[Rental["Rental unit type"].isin([
    "Apartment - 1 bedroom",
    "Apartment - 2 bedrooms",
    "Apartment - 3 bedrooms"  # include only if it exists
])]



Rental_pivot = Rental.pivot_table(
    index=["GEO", "Year", "Quarter"],
    columns="Rental unit type",
    values="Rental_value",
    aggfunc="mean"
).reset_index()

Rental_pivot.head()

Rental unit type,GEO,Year,Quarter,Apartment - 1 bedroom,Apartment - 2 bedrooms
0,"Abbotsford - Mission, Census metropolitan area...",2020,1,1120.0,1330.0
1,"Abbotsford - Mission, Census metropolitan area...",2020,2,1120.0,1380.0
2,"Abbotsford - Mission, Census metropolitan area...",2020,3,1120.0,1370.0
3,"Abbotsford - Mission, Census metropolitan area...",2020,4,1190.0,1340.0
4,"Abbotsford - Mission, Census metropolitan area...",2021,1,1200.0,1580.0

In [15]:
#Loading CPI data

CPI = pd.read_csv("/Users/nyadual/Desktop/Canada_Cost_of_Living/Consumer_Price-Index_databaseLoadingData.csv")
CPI.head()

,REF_DATE,GEO,DGUID,Products and product groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,Jan-20,Newfoundland and Labrador,2016A000210,All-items,2002=100,17,units,0,v41691244,3.2,140.0,NaN,NaN,NaN,1
1,Feb-20,Newfoundland and Labrador,2016A000210,All-items,2002=100,17,units,0,v41691244,3.2,140.3,NaN,NaN,NaN,1
2,Mar-20,Newfoundland and Labrador,2016A000210,All-items,2002=100,17,units,0,v41691244,3.2,139.2,NaN,NaN,NaN,1
3,Apr-20,Newfoundland and Labrador,2016A000210,All-items,2002=100,17,units,0,v41691244,3.2,137.6,NaN,NaN,NaN,1
4,May-20,Newfoundland and Labrador,2016A000210,All-items,2002=100,17,units,0,v41691244,3.2,138.2,NaN,NaN,NaN,1

In [16]:
#Cleaning CPI data

#Droping the unwanted columns and keeping the wanted
CPI = CPI[["REF_DATE", "GEO", "Products and product groups", "VALUE"]]

#Renaming the columns
CPI = CPI.rename(columns={"VALUE": "CPI_Value"})

# Convert date
CPI["REF_DATE"] = pd.to_datetime(CPI["REF_DATE"],format="%b-%y")

CPI["Year"] = CPI["REF_DATE"].dt.year
CPI["Quarter"] = CPI["REF_DATE"].dt.quarter

# Clean GEO
CPI["GEO"] = CPI["GEO"].str.replace(",.*", "", regex=True).str.strip()

CPI.head()

,REF_DATE,GEO,Products and product groups,CPI_Value,Year,Quarter
0,2020-01-01,Newfoundland and Labrador,All-items,140.0,2020,1
1,2020-02-01,Newfoundland and Labrador,All-items,140.3,2020,1
2,2020-03-01,Newfoundland and Labrador,All-items,139.2,2020,1
3,2020-04-01,Newfoundland and Labrador,All-items,137.6,2020,2
4,2020-05-01,Newfoundland and Labrador,All-items,138.2,2020,2

['Apartment - 1 bedroom' 'Apartment - 2 bedrooms' 'Room']

In [ ]:
#merging the two datasets i.e Rental and CPI